# Generated by Django 4.2 on 2023-05-15 15:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingSphere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=uuid.uuid4, max_length=36, null=True, unique=True, verbose_name='Код')),
                ('slug', models.SlugField(max_length=255, verbose_name='URL')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Время')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='meetopia.category', verbose_name='Категории')),
                ('cuisine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='meetopia.cuisine', verbose_name='Вид кухни')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='meetopia.place', verbose_name='Места')),
            ],
            options={
                'verbose_name': 'Встречи',
                'verbose_name_plural': 'Встречи',
            },
        ),
    ]
