# Generated by Django 4.2 on 2023-05-17 19:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('meetopia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingsphere',
            name='code',
            field=models.CharField(default=uuid.uuid4, max_length=36, null=True, verbose_name='Код'),
        ),
    ]
